### ISSUE TITLE
favicon reset after some time

### ISSUE THREAD

**Issue by GarrySong** [ErikvdVen/kpd-custom-theme#1]
Upon first Kibana access, favicon is set properly. But, if I switch to another browser tab, and then back to Kibana, the favicon is replaced back to Kibana's default.

**Comment by ErikvdVen** [comment]
@GarrySong Could you tell me what kind of operating system you are using and which browser? So i can try to reproduce the issue, cause I cannot reproduce it on a Mac using Google Chrome

**Comment by GarrySong** [comment]
Kibana: v5.6.0 OS: Ubuntu 16.04
tested on Browser: Chrome v62.0.3202.75 (32bit) OS: Windows 10
tested on Browser: Chrome v62.0.3202.75 (64bit) OS: Ubuntu 16:04

**Comment by GarrySong** [comment]
I tested on Firefox 56.0 (64bit) on Ubuntu 16:04, the bug did not exist.

**Comment by ErikvdVen** [comment]
To be honest I wasn't able to reproduce your issue. I tried the development version and the Debian package of Elasticsearch with Kibana. I tried to reproduce it with Chrome on Mac OS Sierra and Windows 10, without success.

It might be a Chrome issue, or an issue within the Kibana application itself, or perhaps a Chrome plugin you are using. You could try to implement the JavaScript I used in another application, check if the issue exists there as well. If so, you could try Stack Overflow if anyone over there knows what might be the issue.

For now I will close this issue. If there is anybody else with the same issue, I'll reopen this issue again. But for now it's just unclear whether the issue is caused by the plugin itself or the software you are running it on.

**Comment by GarrySong** [comment]
Your clue about Chrome plugin helped. It is my Tab Suspender extension that is causing the favicon to be reloaded when clicking on the tab.
